import type { ProviderDefinition } from "./types";

export const PROVIDER_REGISTRY: ProviderDefinition[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    description: "Claude models — reasoning, code, and general purpose",
    docsUrl: "https://docs.anthropic.com",
    iconColor: "#D97757",
    ocApi: "anthropic-messages",
    supportsCustomEndpoint: true,
    supportsAccessToken: false,
    defaultBaseUrl: "https://api.anthropic.com",
    models: [
      { id: "claude-opus-4-6-20260301", name: "Claude Opus 4.6", category: "reasoning", contextWindow: 200000, costTier: "high", badges: ["Reasoning", "Latest"] },
      { id: "claude-sonnet-4-6-20260301", name: "Claude Sonnet 4.6", category: "general", contextWindow: 200000, costTier: "mid", badges: ["Balanced", "Latest"] },
      { id: "claude-opus-4-5-20250414", name: "Claude Opus 4.5", category: "reasoning", contextWindow: 200000, costTier: "high", badges: ["Reasoning"] },
      { id: "claude-sonnet-4-5-20250414", name: "Claude Sonnet 4.5", category: "general", contextWindow: 200000, costTier: "mid", badges: ["Balanced"] },
      { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5", category: "fast", contextWindow: 200000, costTier: "low", badges: ["Fast", "Cheap"] },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    description: "GPT models — multimodal, reasoning, and general purpose",
    docsUrl: "https://platform.openai.com/docs",
    iconColor: "#10A37F",
    ocApi: "openai",
    supportsCustomEndpoint: true,
    supportsAccessToken: false,
    models: [
      { id: "gpt-4.1", name: "GPT-4.1", category: "general", contextWindow: 1047576, costTier: "mid", badges: ["1M Context", "Latest"] },
      { id: "gpt-4.1-mini", name: "GPT-4.1 Mini", category: "fast", contextWindow: 1047576, costTier: "low", badges: ["1M Context", "Fast"] },
      { id: "gpt-4o", name: "GPT-4o", category: "multimodal", contextWindow: 128000, costTier: "mid", badges: ["Multimodal"] },
      { id: "o3", name: "o3", category: "reasoning", contextWindow: 200000, costTier: "high", badges: ["Reasoning", "Latest"] },
      { id: "o4-mini", name: "o4-mini", category: "reasoning", contextWindow: 200000, costTier: "mid", badges: ["Reasoning", "Fast"] },
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    description: "Search-augmented models with real-time web access",
    docsUrl: "https://docs.perplexity.ai",
    iconColor: "#20808D",
    ocApi: "openai",
    defaultBaseUrl: "https://api.perplexity.ai",
    supportsCustomEndpoint: false,
    supportsAccessToken: false,
    models: [
      { id: "sonar-pro", name: "Sonar Pro", category: "search", contextWindow: 200000, costTier: "mid", badges: ["Web Search", "Citations"] },
      { id: "sonar", name: "Sonar", category: "search", contextWindow: 128000, costTier: "low", badges: ["Web Search", "Fast"] },
    ],
  },
  {
    id: "google",
    name: "Google",
    description: "Gemini models — multimodal and high-speed inference",
    docsUrl: "https://ai.google.dev/docs",
    iconColor: "#4285F4",
    ocApi: "google",
    supportsCustomEndpoint: false,
    supportsAccessToken: false,
    models: [
      { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", category: "reasoning", contextWindow: 1000000, costTier: "high", badges: ["1M Context", "Reasoning"] },
      { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", category: "fast", contextWindow: 1000000, costTier: "low", badges: ["1M Context", "Fast", "Latest"] },
      { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", category: "fast", contextWindow: 1000000, costTier: "low", badges: ["1M Context", "Fast"] },
    ],
  },
  {
    id: "mistral",
    name: "Mistral",
    description: "European open-source models — fast and efficient",
    docsUrl: "https://docs.mistral.ai",
    iconColor: "#FF7000",
    ocApi: "mistral",
    supportsCustomEndpoint: false,
    supportsAccessToken: false,
    models: [
      { id: "mistral-large-latest", name: "Mistral Large", category: "general", contextWindow: 128000, costTier: "mid", badges: ["EU", "General"] },
      { id: "mistral-medium-latest", name: "Mistral Medium", category: "general", contextWindow: 128000, costTier: "mid", badges: ["EU", "Balanced"] },
      { id: "codestral-latest", name: "Codestral", category: "code", contextWindow: 32000, costTier: "mid", badges: ["EU", "Code"] },
      { id: "mistral-small-latest", name: "Mistral Small", category: "fast", contextWindow: 128000, costTier: "low", badges: ["EU", "Fast"] },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    description: "Ultra-fast inference for open-source models",
    docsUrl: "https://console.groq.com/docs",
    iconColor: "#F55036",
    ocApi: "openai",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    supportsCustomEndpoint: false,
    supportsAccessToken: false,
    models: [
      { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B", category: "general", contextWindow: 128000, costTier: "low", badges: ["Fast", "Open Source"] },
      { id: "mixtral-8x7b-32768", name: "Mixtral 8x7B", category: "general", contextWindow: 32768, costTier: "low", badges: ["Fast", "MoE"] },
      { id: "gemma2-9b-it", name: "Gemma 2 9B", category: "fast", contextWindow: 8192, costTier: "low", badges: ["Fast", "Compact"] },
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    description: "Unified gateway to 200+ models from all providers",
    docsUrl: "https://openrouter.ai/docs",
    iconColor: "#6366F1",
    ocApi: "openai",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    supportsCustomEndpoint: false,
    supportsAccessToken: false,
    models: [
      { id: "openrouter/auto", name: "Auto (best available)", category: "general", contextWindow: 128000, costTier: "mid", badges: ["Auto-route"] },
    ],
  },
  {
    id: "ollama",
    name: "Ollama",
    description: "Run open-source models locally on your machine",
    docsUrl: "https://ollama.com",
    iconColor: "#1A1A1A",
    ocApi: "openai-responses",
    defaultBaseUrl: "http://localhost:11434/v1",
    supportsCustomEndpoint: true,
    supportsAccessToken: false,
    models: [
      { id: "llama3.3", name: "Llama 3.3", category: "general", contextWindow: 128000, costTier: "low", badges: ["Local", "Free"] },
      { id: "codellama", name: "Code Llama", category: "code", contextWindow: 16384, costTier: "low", badges: ["Local", "Code"] },
      { id: "mistral", name: "Mistral 7B", category: "fast", contextWindow: 32768, costTier: "low", badges: ["Local", "Fast"] },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    description: "Advanced reasoning and coding models",
    docsUrl: "https://platform.deepseek.com/docs",
    iconColor: "#4D6BFE",
    ocApi: "openai",
    defaultBaseUrl: "https://api.deepseek.com/v1",
    supportsCustomEndpoint: false,
    supportsAccessToken: false,
    models: [
      { id: "deepseek-chat", name: "DeepSeek V3", category: "general", contextWindow: 128000, costTier: "low", badges: ["Balanced"] },
      { id: "deepseek-reasoner", name: "DeepSeek R1", category: "reasoning", contextWindow: 128000, costTier: "low", badges: ["Reasoning", "CoT"] },
    ],
  },
  {
    id: "together",
    name: "Together AI",
    description: "Fast inference for open-source models at scale",
    docsUrl: "https://docs.together.ai",
    iconColor: "#0EA5E9",
    ocApi: "openai",
    defaultBaseUrl: "https://api.together.xyz/v1",
    supportsCustomEndpoint: false,
    supportsAccessToken: false,
    models: [
      { id: "meta-llama/Llama-3.3-70B-Instruct-Turbo", name: "Llama 3.3 70B Turbo", category: "general", contextWindow: 128000, costTier: "low", badges: ["Fast", "Open Source"] },
      { id: "Qwen/Qwen2.5-72B-Instruct-Turbo", name: "Qwen 2.5 72B Turbo", category: "general", contextWindow: 128000, costTier: "low", badges: ["Multilingual"] },
    ],
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    description: "Optimized inference for fine-tuned and open models",
    docsUrl: "https://docs.fireworks.ai",
    iconColor: "#FF6B2B",
    ocApi: "openai",
    defaultBaseUrl: "https://api.fireworks.ai/inference/v1",
    supportsCustomEndpoint: false,
    supportsAccessToken: false,
    models: [
      { id: "accounts/fireworks/models/llama-v3p3-70b-instruct", name: "Llama 3.3 70B", category: "general", contextWindow: 128000, costTier: "low", badges: ["Fast"] },
    ],
  },
  {
    id: "cohere",
    name: "Cohere",
    description: "Enterprise RAG and retrieval-augmented models",
    docsUrl: "https://docs.cohere.com",
    iconColor: "#39594D",
    ocApi: "openai",
    defaultBaseUrl: "https://api.cohere.ai/compatibility/v1",
    supportsCustomEndpoint: false,
    supportsAccessToken: false,
    models: [
      { id: "command-r-plus", name: "Command R+", category: "general", contextWindow: 128000, costTier: "mid", badges: ["RAG", "Enterprise"] },
      { id: "command-r", name: "Command R", category: "fast", contextWindow: 128000, costTier: "low", badges: ["RAG", "Fast"] },
    ],
  },
  {
    id: "amazon-bedrock",
    name: "Amazon Bedrock",
    description: "AWS-managed access to Claude, Titan, and more",
    docsUrl: "https://docs.aws.amazon.com/bedrock",
    iconColor: "#FF9900",
    ocApi: "bedrock",
    supportsCustomEndpoint: true,
    supportsAccessToken: false,
    models: [
      { id: "anthropic.claude-sonnet-4-5-20250414-v1:0", name: "Claude Sonnet 4.5 (Bedrock)", category: "general", contextWindow: 200000, costTier: "mid", badges: ["AWS", "Managed"] },
      { id: "amazon.titan-text-premier-v1:0", name: "Titan Text Premier", category: "general", contextWindow: 32000, costTier: "low", badges: ["AWS", "Native"] },
    ],
  },
  {
    id: "azure-openai",
    name: "Azure OpenAI",
    description: "Enterprise-grade OpenAI models via Azure",
    docsUrl: "https://learn.microsoft.com/azure/ai-services/openai",
    iconColor: "#0078D4",
    ocApi: "openai",
    supportsCustomEndpoint: true,
    supportsAccessToken: false,
    models: [
      { id: "gpt-4o", name: "GPT-4o (Azure)", category: "multimodal", contextWindow: 128000, costTier: "mid", badges: ["Azure", "Enterprise"] },
    ],
  },
  {
    id: "cloudflare",
    name: "Cloudflare Workers AI",
    description: "Edge-deployed open models on Cloudflare network",
    docsUrl: "https://developers.cloudflare.com/workers-ai",
    iconColor: "#F48120",
    ocApi: "openai",
    supportsCustomEndpoint: true,
    supportsAccessToken: false,
    models: [
      { id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", name: "Llama 3.3 70B (Edge)", category: "general", contextWindow: 32000, costTier: "low", badges: ["Edge", "Fast"] },
    ],
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    description: "GPU-optimized inference for enterprise AI",
    docsUrl: "https://build.nvidia.com",
    iconColor: "#76B900",
    ocApi: "openai",
    defaultBaseUrl: "https://integrate.api.nvidia.com/v1",
    supportsCustomEndpoint: true,
    supportsAccessToken: false,
    models: [
      { id: "meta/llama-3.1-405b-instruct", name: "Llama 3.1 405B", category: "reasoning", contextWindow: 128000, costTier: "high", badges: ["405B", "Enterprise"] },
    ],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "Inference API for thousands of open models",
    docsUrl: "https://huggingface.co/docs/api-inference",
    iconColor: "#FFD21E",
    ocApi: "openai",
    defaultBaseUrl: "https://api-inference.huggingface.co/v1",
    supportsCustomEndpoint: true,
    supportsAccessToken: false,
    models: [
      { id: "meta-llama/Llama-3.3-70B-Instruct", name: "Llama 3.3 70B", category: "general", contextWindow: 128000, costTier: "low", badges: ["Open Source"] },
    ],
  },
  {
    id: "xai",
    name: "xAI",
    description: "Grok models — conversational AI with real-time knowledge",
    docsUrl: "https://docs.x.ai",
    iconColor: "#000000",
    ocApi: "openai",
    defaultBaseUrl: "https://api.x.ai/v1",
    supportsCustomEndpoint: false,
    supportsAccessToken: false,
    models: [
      { id: "grok-3", name: "Grok 3", category: "reasoning", contextWindow: 131072, costTier: "mid", badges: ["Reasoning", "Latest"] },
      { id: "grok-3-mini", name: "Grok 3 Mini", category: "fast", contextWindow: 131072, costTier: "low", badges: ["Fast"] },
    ],
  },
  {
    id: "litellm",
    name: "LiteLLM",
    description: "Unified proxy for 100+ LLM providers with OpenAI-compatible API",
    docsUrl: "https://docs.litellm.ai",
    iconColor: "#1E40AF",
    ocApi: "openai",
    supportsCustomEndpoint: true,
    supportsAccessToken: false,
    models: [
      { id: "litellm/auto", name: "Auto (best available)", category: "general", contextWindow: 128000, costTier: "mid", badges: ["Multi-Provider"] },
    ],
  },
  {
    id: "custom",
    name: "Custom / Self-hosted",
    description: "Connect to vLLM, LiteLLM, or any OpenAI-compatible endpoint",
    docsUrl: "",
    iconColor: "#6B7280",
    ocApi: "openai",
    supportsCustomEndpoint: true,
    supportsAccessToken: false,
    models: [],
  },
];

export const getProviderById = (id: string) =>
  PROVIDER_REGISTRY.find((p) => p.id === id) ?? null;
