import type { SkillDefinition } from "./types";

export const SKILLS_REGISTRY: SkillDefinition[] = [
  { id: "email-sender", name: "Email Sender", description: "Send emails via SMTP, SendGrid, or Mailgun", category: "communication", icon: "📧", author: "OpenClaw", version: "1.2.0", rating: 4.8, installs: 12500, tags: ["email", "smtp", "sendgrid"] },
  { id: "web-scraper", name: "Web Scraper", description: "Extract data from websites with intelligent parsing", category: "data", icon: "🕸️", author: "OpenClaw", version: "2.0.1", rating: 4.6, installs: 9800, tags: ["scraping", "web", "extraction"] },
  { id: "calendar-manager", name: "Calendar Manager", description: "Manage Google Calendar, Outlook, and CalDAV events", category: "productivity", icon: "📅", author: "OpenClaw", version: "1.5.0", rating: 4.7, installs: 7200, tags: ["calendar", "scheduling", "events"] },
  { id: "code-reviewer", name: "Code Reviewer", description: "Automated code review with best practice suggestions", category: "development", icon: "🔍", author: "OpenClaw", version: "3.1.0", rating: 4.9, installs: 15300, tags: ["code", "review", "quality"] },
  { id: "social-poster", name: "Social Media Poster", description: "Post to Twitter, LinkedIn, Instagram, and Facebook", category: "marketing", icon: "📱", author: "OpenClaw", version: "1.8.2", rating: 4.5, installs: 6100, tags: ["social", "marketing", "posting"] },
  { id: "invoice-generator", name: "Invoice Generator", description: "Create and send professional invoices with PDF export", category: "finance", icon: "💰", author: "OpenClaw", version: "1.3.0", rating: 4.4, installs: 4200, tags: ["invoice", "billing", "pdf"] },
  { id: "file-converter", name: "File Converter", description: "Convert between PDF, DOCX, CSV, JSON, and more", category: "productivity", icon: "🔄", author: "OpenClaw", version: "2.2.0", rating: 4.6, installs: 8700, tags: ["conversion", "files", "format"] },
  { id: "database-query", name: "Database Query", description: "Query PostgreSQL, MySQL, MongoDB, and Redis", category: "data", icon: "🗃️", author: "OpenClaw", version: "1.4.1", rating: 4.7, installs: 5400, tags: ["database", "sql", "nosql"] },
  { id: "ci-cd-trigger", name: "CI/CD Trigger", description: "Trigger GitHub Actions, GitLab CI, and Jenkins pipelines", category: "development", icon: "🚀", author: "OpenClaw", version: "1.1.0", rating: 4.3, installs: 3200, tags: ["ci", "cd", "pipeline", "deployment"] },
  { id: "sentry-monitor", name: "Sentry Monitor", description: "Monitor and manage Sentry error tracking", category: "security", icon: "🛡️", author: "OpenClaw", version: "1.0.0", rating: 4.5, installs: 2800, tags: ["monitoring", "errors", "sentry"] },
  { id: "translation-service", name: "Translation Service", description: "Translate text using DeepL, Google Translate, or OpenAI", category: "communication", icon: "🌐", author: "OpenClaw", version: "1.6.0", rating: 4.8, installs: 11200, tags: ["translation", "i18n", "localization"] },
  { id: "image-generator", name: "Image Generator", description: "Generate images with DALL-E, Stable Diffusion, or Midjourney API", category: "marketing", icon: "🎨", author: "OpenClaw", version: "2.0.0", rating: 4.9, installs: 18000, tags: ["image", "generation", "ai", "creative"] },
];
